import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
// Static import so the index is bundled INTO the serverless function. Files under
// public/ are CDN assets and are NOT traced into the function bundle, so a runtime
// fs read of them 500s on Vercel (a local fs read would falsely pass). The index is
// generated by prebuild and committed, so this import always resolves.
import searchIndexJson from "../../../../public/search-index.json";

// Keyless onsite search. Replaces the previous Google Custom Search Engine proxy,
// which returned HTTP 500 ("Request contains an invalid argument.") in production
// whenever the external API key/cx was missing or invalid.

interface IndexEntry {
	url: string;
	path: string;
	title: string;
	type: string;
	keywords: string;
}

const entries: IndexEntry[] =
	(searchIndexJson as { entries?: IndexEntry[] }).entries || [];

const norm = (s: string) =>
	s
		.toLowerCase()
		.replace(/[-_/]+/g, " ")
		.replace(/\s+/g, " ")
		.trim();

function rank(entries: IndexEntry[], query: string) {
	const nq = norm(query);
	if (!nq) return [];
	const tokens = nq.split(" ").filter(Boolean);
	return entries
		.map((e) => {
			const t = norm(e.title);
			const k = norm(e.keywords);
			const p = norm(e.path);
			let score = 0;
			if (t.includes(nq)) score += 12;
			if (k.includes(nq)) score += 8;
			if (p.includes(nq)) score += 6;
			for (const tok of tokens) {
				if (t.includes(tok)) score += 3;
				if (k.includes(tok)) score += 2;
				if (p.includes(tok)) score += 1;
			}
			if (
				score > 0 &&
				["home", "hub", "service", "business", "action"].includes(e.type)
			)
				score += 1;
			return { e, score };
		})
		.filter((x) => x.score > 0)
		.sort((a, b) => b.score - a.score)
		.map(({ e }) => ({
			title: e.title,
			url: e.url,
			snippet: `${e.title}, ZA Support, Johannesburg.`,
		}));
}

export async function GET(req: NextRequest) {
	const q = req.nextUrl.searchParams.get("q")?.trim();
	const start = Math.max(
		1,
		parseInt(req.nextUrl.searchParams.get("start") || "1", 10) || 1,
	);
	if (!q) {
		return NextResponse.json({ error: "Missing query" }, { status: 400 });
	}
	const ranked = rank(entries, q);
	return NextResponse.json({
		total: ranked.length,
		results: ranked.slice(start - 1, start - 1 + 10),
	});
}
