#!/usr/bin/env python3
"""
ZA Support Session Feedback System
Run at END of every Claude Code session.
Reads validation.log, generates report, emails courtney@zasupport.com, updates learnings.
"""

import os, json, requests, subprocess
from datetime import datetime
from pathlib import Path

BASE = os.path.expanduser("~/Developer/new-zas-website")
VLOG = os.path.join(BASE, "media/workshop/logs/validation.log")
REPORTS = os.path.join(BASE, "docs/seo/session-reports")
LEARNINGS = os.path.join(BASE, "docs/seo/cumulative-learnings.md")
NOTIFY = "courtney@zasupport.com"

def get_ms_token():
    env_file = os.path.expanduser("~/.za-support.env")
    if os.path.exists(env_file):
        with open(env_file) as f:
            for line in f:
                if line.startswith("export "):
                    key, _, val = line[7:].partition("=")
                    os.environ[key.strip()] = val.strip().strip('"')
    refresh = os.environ.get("MS_GRAPH_REFRESH_TOKEN", "")
    client = os.environ.get("MS_CLIENT_ID", "02d82633-39c6-4456-bb06-43ba34c6ee91")
    secret = os.environ.get("MS_CLIENT_SECRET", "")
    if not refresh:
        return ""
    try:
        r = requests.post("https://login.microsoftonline.com/common/oauth2/v2.0/token",
            data={"grant_type": "refresh_token", "client_id": client,
                  "client_secret": secret, "refresh_token": refresh,
                  "scope": "https://graph.microsoft.com/Mail.Send"})
        return r.json().get("access_token", "")
    except Exception:
        return ""

def parse_validation_log():
    if not os.path.exists(VLOG):
        return {"entries": [], "pass": 0, "fail": 0, "not_installed": 0}

    entries = []
    with open(VLOG) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            entries.append(line)

    pass_count = sum(1 for e in entries if "PASS" in e or "INSTALLED:" in e)
    fail_count = sum(1 for e in entries if "FAIL" in e)
    not_installed = sum(1 for e in entries if "NOT INSTALLED" in e or "NOT DEPLOYED" in e or "NOT_FOUND" in e)

    return {
        "entries": entries,
        "pass": pass_count,
        "fail": fail_count,
        "not_installed": not_installed
    }

def generate_report(session_context=""):
    ts = datetime.now().strftime("%d/%m/%Y %H:%M SAST")
    log = parse_validation_log()

    done = [e for e in log["entries"] if "PASS" in e or "INSTALLED:" in e or "DEPLOYED" in e or "EXISTS" in e]
    failed = [e for e in log["entries"] if "FAIL" in e]
    not_installed = [e for e in log["entries"] if "NOT INSTALLED" in e or "NOT DEPLOYED" in e or "NOT_FOUND" in e]

    report = f"""# Session Report — {ts}

## SUMMARY
- Components tested: {len(log['entries'])}
- Passed: {log['pass']}
- Failed: {log['fail']}
- Not installed/deployed: {log['not_installed']}

## CONFIRMED WORKING (real-data tested)
"""
    for item in done:
        report += f"- {item}\n"

    report += "\n## FAILED (needs attention)\n"
    for item in failed:
        report += f"- {item}\n"
    if not failed:
        report += "- None\n"

    report += "\n## NOT YET INSTALLED/DEPLOYED\n"
    for item in not_installed:
        report += f"- {item}\n"
    if not not_installed:
        report += "- None\n"

    report += f"""
## LEARNINGS FROM THIS SESSION
(Add specific learnings before sending)

## CONTEXT
{session_context if session_context else 'SEO Infrastructure Buildout 07/04/2026'}

## NEXT STEPS
(List what needs to happen next)

*Auto-generated by za_session_feedback.py | {ts}*
"""
    return report

def save_report(report):
    os.makedirs(REPORTS, exist_ok=True)
    filename = f"session-report-{datetime.now().strftime('%Y%m%d-%H%M')}.md"
    path = os.path.join(REPORTS, filename)
    with open(path, "w") as f:
        f.write(report)
    return path

def update_learnings(report):
    """Append key findings to cumulative learnings file."""
    os.makedirs(os.path.dirname(LEARNINGS), exist_ok=True)
    ts = datetime.now().strftime("%d/%m/%Y %H:%M SAST")

    with open(LEARNINGS, "a") as f:
        f.write(f"\n## Session — {ts}\n")
        log = parse_validation_log()
        f.write(f"- Passed: {log['pass']} | Failed: {log['fail']} | Not installed: {log['not_installed']}\n")
        for entry in log["entries"]:
            if "FAIL" in entry or "NOT_FOUND" in entry:
                f.write(f"- ISSUE: {entry}\n")

def email_report(report, token):
    """Send report to courtney@zasupport.com via MS Graph."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    ts = datetime.now().strftime("%d/%m/%Y %H:%M")

    payload = {
        "message": {
            "subject": f"Claude Code Session Report — {ts}",
            "body": {"contentType": "HTML", "content": f"<pre style='font-family:Arial,sans-serif;font-size:12pt'>{report}</pre>"},
            "toRecipients": [{"emailAddress": {"address": NOTIFY}}]
        }
    }

    r = requests.post("https://graph.microsoft.com/v1.0/me/sendMail",
                      headers=headers, json=payload)
    return r.status_code == 202

def git_commit_report(report_path):
    """Commit session report to git."""
    try:
        subprocess.run(["git", "add", report_path, LEARNINGS, VLOG],
                      cwd=BASE, capture_output=True)
        subprocess.run(["git", "commit", "-m",
                       f"chore: session report {datetime.now().strftime('%Y%m%d %H%M')}"],
                      cwd=BASE, capture_output=True)
    except Exception:
        pass

def run(session_context=""):
    print("=== Generating Session Feedback ===")

    report = generate_report(session_context)
    report_path = save_report(report)
    print(f"Report saved: {report_path}")

    update_learnings(report)
    print(f"Learnings updated: {LEARNINGS}")

    token = get_ms_token()
    if token:
        if email_report(report, token):
            print(f"Report emailed to {NOTIFY}")
        else:
            print("Email send failed — report saved locally")
    else:
        print("No MS Graph token — report saved locally only")

    git_commit_report(report_path)
    print("Report committed to git")
    print("=== Session Feedback Complete ===")

if __name__ == "__main__":
    import sys
    context = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else ""
    run(context)
