import { expect, test } from "@playwright/test";

// Onsite search acceptance (Handoff §9-C, §10). Runs against BASE_URL (preview build
// with public/search-index.json generated by prebuild). Verifies the keyless index.

test.describe("onsite search", () => {
	test('"Logic board" returns a logic-board result', async ({ page }) => {
		await page.goto("/search?q=Logic%20board");
		await expect(
			page.getByRole("heading", { name: /Search results for/i }),
		).toBeVisible();
		// at least one result links to logic-board content
		const link = page.locator('a[href*="logic-board"]').first();
		await expect(link).toBeVisible();
	});

	test('hyphen variant "logic-board" also works', async ({ page }) => {
		await page.goto("/search?q=logic-board");
		await expect(page.locator('a[href*="logic-board"]').first()).toBeVisible();
	});

	test("URL-encoded multi-word query works", async ({ page }) => {
		await page.goto("/search?q=MacBook%20liquid%20damage");
		await expect(
			page.locator('a[href*="liquid-damage"]').first(),
		).toBeVisible();
	});

	test("empty query shows the prompt, no error", async ({ page }) => {
		await page.goto("/search");
		await expect(
			page.getByRole("heading", { name: /Search ZA Support/i }),
		).toBeVisible();
	});

	test("no-result query shows a graceful empty state", async ({ page }) => {
		await page.goto("/search?q=xqzptvwlmn");
		await expect(page.getByText(/No results found/i)).toBeVisible();
	});

	test("search page is noindex (no crawl trap)", async ({ page }) => {
		const res = await page.goto("/search?q=battery");
		expect(res?.status()).toBe(200);
		const robots = await page
			.locator('meta[name="robots"]')
			.getAttribute("content");
		expect(robots).toMatch(/noindex/i);
	});

	test("keyboard: type + Enter submits and shows results", async ({ page }) => {
		await page.goto("/search");
		const input = page.locator('input[name="q"]');
		await input.fill("battery");
		await input.press("Enter");
		await expect(page).toHaveURL(/q=battery/);
		await expect(page.locator('a[href*="battery"]').first()).toBeVisible();
	});
});
