import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://zasupport.com';
  const now = new Date();

  return [
    // Homepage
    { url: base, lastModified: now, changeFrequency: 'weekly', priority: 1.0 },

    // High-intent symptom pages
    { url: `${base}/macbook-not-turning-on`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },

    // Priority hubs
    { url: `${base}/liquid-damage`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/logic-board-repair`, lastModified: now, changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/iphone-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/apple-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/apple-support`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/macbook-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/book`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/macbook-air-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/macbook-pro-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/imac-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/imac-repair/screen`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/imac-repair/ram-upgrade`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/imac-repair/ssd-upgrade`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // MacBook Pro repair sub-pages
    { url: `${base}/macbook-pro-repair/battery`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-pro-repair/screen`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-pro-repair/keyboard`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Battery replacement (top-level)
    { url: `${base}/battery-replacement`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // MacBook repair sub-pages
    { url: `${base}/macbook-repair/ssd-upgrade`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/ram-upgrade`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/battery`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/screen`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/keyboard`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/trackpad`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/charging-port`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/liquid-damage`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/logic-board`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/data-recovery`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/virus-removal`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Liquid damage sub-pages
    { url: `${base}/liquid-damage/macbook-pro`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/macbook-air`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/iphone`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/ipad`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/liquid-damage/apple-watch`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/liquid-damage/imac`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Logic board sub-pages
    { url: `${base}/logic-board-repair/macbook-pro`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/logic-board-repair/macbook-air`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/logic-board-repair/imac`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/mac-mini`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Logic board model-specific pages
    { url: `${base}/logic-board-repair/macbook-pro-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-14-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-16-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-13-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // Logic board suburb pages
    { url: `${base}/logic-board-repair/sandton`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/rosebank`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/midrand`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/randburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/fourways`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/bryanston`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/kempton-park`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // Screen repair hub
    { url: `${base}/screen-repair`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },

    // Liquid damage model-specific pages
    { url: `${base}/liquid-damage/macbook-pro-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-13-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-14-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-16-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/mac-mini`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // Battery replacement model pages
    { url: `${base}/battery-replacement/macbook-pro`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/macbook-air`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/imac`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/iphone`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/mac-mini`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Battery replacement suburb pages
    { url: `${base}/battery-replacement/sandton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/rosebank`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/fourways`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/bryanston`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/midrand`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/randburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/kempton-park`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Screen repair model pages
    { url: `${base}/screen-repair/macbook-pro`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-13-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-air`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/imac`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/iphone`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // Screen repair suburb pages
    { url: `${base}/screen-repair/sandton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/rosebank`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/bryanston`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/fourways`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/midrand`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/randburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/kempton-park`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/pretoria`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/centurion`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/morningside`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/rivonia`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/sunninghill`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/paulshof`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/northcliff`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/houghton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/parkhurst`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // iPhone screen repair suburb pages
    { url: `${base}/iphone-repair/screen/sandton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/rosebank`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/fourways`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/bryanston`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/midrand`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/randburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/kempton-park`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Liquid damage suburb pages
    { url: `${base}/liquid-damage/sandton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/rosebank`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/fourways`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/bryanston`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/midrand`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/randburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/kempton-park`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // iPhone repair sub-pages
    { url: `${base}/iphone-repair/screen`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/battery`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/charging`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/iphone-repair/back-glass`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/iphone-repair/camera`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/iphone-repair/liquid-damage`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // iPad repair sub-pages
    { url: `${base}/ipad-repair`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/ipad-repair/screen`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/ipad-repair/battery`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/ipad-repair/charging`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Apple Watch repair
    { url: `${base}/apple-watch-repair`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // AirPods repair
    { url: `${base}/airpods-repair`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Apple accessories repair
    { url: `${base}/accessories-repair`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Mac Mini repair
    { url: `${base}/mac-mini-repair`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },

    // Business services — sector pages
    { url: `${base}/enterprise`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/sme-support`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/medical-it`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/government`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/jamf-mdm`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/apple-specialist`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/it-support`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/investec`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/managed-services/unifi-networking`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/managed-services/wealth-management`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/apple-support/medical-practices`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/apple-support/business`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/apple-support/enterprise`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },

    // iPad repair — additional sub-page
    { url: `${base}/ipad-repair/liquid-damage`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Assessment Process — transparent pricing page
    { url: `${base}/no-fix-no-fee`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },

    // Author pages
    { url: `${base}/author/courtney-bentley`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/author/mary`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },

    // Core pages
    { url: `${base}/about`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/services`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/contact`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/privacy`, lastModified: now, changeFrequency: 'yearly', priority: 0.4 },
    { url: `${base}/terms`, lastModified: now, changeFrequency: 'yearly', priority: 0.4 },

    // Blog
    { url: `${base}/blog`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${base}/blog/macbook-load-shedding-damage`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/what-to-do-macbook-liquid-damage`, lastModified: now, changeFrequency: 'yearly', priority: 0.6 },
    { url: `${base}/blog/why-rice-does-not-work`, lastModified: now, changeFrequency: 'yearly', priority: 0.6 },
    { url: `${base}/blog/jamf-mdm-guide-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.6 },
    { url: `${base}/blog/macbook-running-slow`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-wont-connect-wifi`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/apple-id-locked-out`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/how-to-speed-up-mac-free`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/mac-not-turning-on-checklist`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-logic-board-repair-cost-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-battery-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-screen-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-wont-charge-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-overheating-fix-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-keyboard-not-working`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/iphone-screen-repair-cost-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.75 },
    { url: `${base}/blog/mac-data-recovery-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-pro-m1-m2-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.75 },
    { url: `${base}/blog/macbook-trackpad-not-clicking`, lastModified: now, changeFrequency: 'yearly', priority: 0.65 },
    { url: `${base}/blog/apple-watch-screen-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/ipad-screen-repair-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/mac-mini-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/how-to-check-macbook-battery-health`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-black-screen-on-startup`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/liquid-damage-macbook-johannesburg-cost`, lastModified: now, changeFrequency: 'yearly', priority: 0.75 },
    { url: `${base}/blog/when-to-replace-vs-repair-macbook`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-ssd-upgrade-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/imac-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-speaker-not-working`, lastModified: now, changeFrequency: 'yearly', priority: 0.65 },
    { url: `${base}/blog/airpods-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-wifi-keeps-disconnecting`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-logic-board-symptoms-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.75 },

    // Auto-generated suburb pages — overnight batch
    { url: `${base}/logic-board-repair/pretoria`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/pretoria`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/pretoria`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/pretoria`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/centurion`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/centurion`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/centurion`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/centurion`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/morningside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/morningside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/morningside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/morningside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/rivonia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/rivonia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/rivonia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/rivonia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/sunninghill`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/sunninghill`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/sunninghill`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/sunninghill`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/paulshof`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/paulshof`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/paulshof`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/paulshof`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/northcliff`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/northcliff`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/northcliff`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/northcliff`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/houghton`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/houghton`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/houghton`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/houghton`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/parkhurst`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/parkhurst`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/parkhurst`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/parkhurst`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/parktown-north`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/parktown-north`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/parktown-north`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/parktown-north`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/greenside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/greenside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/greenside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/greenside`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/craighall`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/craighall`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/craighall`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/craighall`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/linden`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/linden`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/linden`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/linden`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/emmarentia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/emmarentia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/emmarentia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/emmarentia`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/melville`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/melville`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/melville`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/melville`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

        { url: `${base}/blog/logic-board-repair-cost-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-not-turning-on-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-not-charging-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-mac-battery-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-screen-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/does-macbook-warranty-cover-water-damage-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-long-macbook-survive-after-water-damage`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/laptop-water-damage-repair-vs-buy-new-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-repair-vs-replacement-water-damage`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-data-recovery-options`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-diy-mistakes-to-avoid`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-repair-cost-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/prevent-macbook-water-damage-protection-tips`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/signs-of-water-damage-macbook-how-to-tell`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/spilled-coffee-on-macbook-what-to-do-right-now`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/can-water-damaged-macbook-be-repaired-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-water-damage-logic-board-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-indicator-what-apple-checks`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-coffee-spill-repair-cost-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-first-aid-steps-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-charging-port-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-logic-board-repair`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-trackpad-not-clicking-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },

    // Complete service/suburb/model pages — auto-synced 30/03/2026
    { url: `${base}/battery-replacement/macbook-pro-13-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-14-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/mac-mini`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-pro-14-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-pro-16-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/macbook-air-m1`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-air-m2`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-air-m3`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-16-inch`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },

    // Troubleshooting guides (HowTo schema — featured snippet targets)
    { url: `${base}/guides`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/guides/macbook-not-turning-on`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-water-damage-what-to-do`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-not-charging`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-overheating-fix`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/macbook-screen-flickering`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-check-macbook-battery-health`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-recover-data-from-dead-macbook`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/macbook-running-slow`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/jamf-mdm-medical-practice-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-dainfern-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-law-firm-apple-mac-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },

    // §194/§223 New suburb pages — TIER 1 ≤20km and TIER 2 20-60km from Hyde Park
    { url: `${base}/logic-board-repair/melrose`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/melrose`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/melrose`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/melrose`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/illovo`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/illovo`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/illovo`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/illovo`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/woodmead`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/woodmead`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/woodmead`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/woodmead`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/kyalami`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/kyalami`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/kyalami`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/kyalami`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/edenvale`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/edenvale`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/edenvale`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/edenvale`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/bedfordview`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/bedfordview`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/bedfordview`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/bedfordview`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/roodepoort`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/roodepoort`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/roodepoort`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/roodepoort`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/boksburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/boksburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/boksburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/boksburg`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/benoni`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/benoni`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/benoni`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/benoni`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/alberton`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/alberton`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/alberton`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/alberton`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/germiston`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/germiston`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/germiston`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/germiston`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/randpark-ridge`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/randpark-ridge`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/randpark-ridge`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/randpark-ridge`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
        { url: `${base}/blog/apple-vs-third-party-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fan-noise-fix-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-wifi-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-swollen-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-recovery-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-not-turning-on-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-morningside-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-swollen-replacement-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-repair-fourways-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-popia-it-provider-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-usb-c-port-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-it-provider-agreement-medical-practice`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-speaker-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-touch-id-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-certified-repair-hyde-park`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/corporate-apple-fleet-management-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m3-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-midrand`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-hinge-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-kernel-panic-fix-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-it-security-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-sandton-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-max-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-flickering-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-pro-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-draining-fast-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-black-screen-fix-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-running-slow-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-not-turning-on-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-camera-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-indicator-check-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-m3-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-repair-bryanston`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-startup-disk-full-fix-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-repair-vs-replacement-guide-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/investec-sandton-apple-support`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-parkhurst`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-to-diagnose-macbook-fault-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-migration-assistant-guide-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-support-financial-services-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-support-small-business-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-backup-time-machine-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-security-setup-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-preventive-maintenance-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/hpcsa-records-mac-backup-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-clean-install-macos-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-cooling-pad-worth-it-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/goodx-mac-support-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/carepoint-mac-support-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-virus-removal-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-emr-mac-support-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/second-hand-mac-check-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/carepoint-macbook-support-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-fusion-drive-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-backlight-ic-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-display-cable-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pmic-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-managed-it-morningside`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-battery-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-fourways`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-medical-practice-gauteng`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-managed-it-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-screen-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-battery-replacement-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-charging-ic-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-midrand`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-melrose`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-ram-upgrade-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-trackpad-ribbon-cable-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-business-manager-setup-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-bryanston`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-houghton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-pro-2019-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-rosebank`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-board-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-firmware-restore-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-wifi-card-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/corporate-mac-onboarding-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-rosebank`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-centurion`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-board-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-fourways`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-midrand`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-rivonia`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-rosebank`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-morningside`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-clean-install-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/tim-cook-steps-down-john-ternus-apple-ceo-south-africa`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/who-is-john-ternus-apple-ceo-engineer`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-ceo-change-johannesburg-business-fleet`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-morningside-medical`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/milpark-hospital-macbook-repair`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/netcare-rosebank-apple-it-support`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/sunninghill-hospital-mac-repair`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/same-day-macbook-repair-doctors-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-midstream-estate`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/jamf-implementation-sandton-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/marketing-agency-imac-support-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/tech-startup-jamf-setup-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fleet-management-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-macbook-encryption-sme-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/charlotte-maxeke-hospital-apple-repair`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/life-fourways-hospital-apple-it`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-fusion-drive-replacement-sandton`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-liquid-damage-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-bryanston-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-screen-repair-rosebank`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-logic-board-failure-signs`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-fourways`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-randburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-much-macbook-repair-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-pro-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-hdmi-not-working-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-short-circuit-repair`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-2020-intel-repair-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-repair-prices-johannesburg-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-price-guide-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-repair-cost-2026`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-cost-johannesburg`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
  ];
}
