import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://zasupport.com';

  return [
    // Existing public articles recovered by the complete posts-key inventory.
    // No fabricated lastModified: this repair changes discovery, not article text.
    { url: `${base}/blog/apple-prepping-ios-26-4-1-update-for-iphone-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/these-are-my-favorite-macbook-neo-accessories-after-one-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/discounted-ipad-pro-hits-apple-refurb-store-with-last-g-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/iphone-18-s-biggest-design-change-will-be-new-colors-sa-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/apple-adds-apple-tv-and-ipad-mini-models-to-obsolete-pr-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/sunday-reboot-addiction-vr-and-how-the-iphone-air-doesn-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/first-ios-26-5-macos-26-5-developer-betas-now-available-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/blog/ipados-26-5-beta-1-now-available-plus-tvos-26-5-watchos-south-africa-2026`, changeFrequency: 'yearly', priority: 0.5 },
    { url: `${base}/mac-data-recovery`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/apple-trade-in-johannesburg`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-trade-in-checklist`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-trade-in-checklist`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/activation-lock-help`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/mac-hacked-what-to-do`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/mac-remote-access-scam-help`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/apple-account-security-help`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/business-mac-security-incident-response`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/digital-evidence-preservation`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/apple-device-forensic-assessment`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/business-device-investigation-consent`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/chain-of-custody-digital-evidence-south-africa`, lastModified: new Date('2026-09-21T00:00:00Z'), changeFrequency: 'monthly', priority: 0.8 },
    // Homepage
    { url: base, changeFrequency: 'weekly', priority: 1.0 },

    // High-intent symptom pages
    { url: `${base}/macbook-not-turning-on`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.95 },

    // Priority hubs
    { url: `${base}/liquid-damage`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/logic-board-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/iphone-repair`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/apple-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/apple-support`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/book`, changeFrequency: 'weekly', priority: 0.9 },

    // Business hub
    { url: `${base}/business`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/business/adobe-creative-cloud-support`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/business/microsoft-365-for-business`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/business/unifi-network-services`, changeFrequency: 'weekly', priority: 0.8 },

    // Answers Q&A hub
    { url: `${base}/answers`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/answers/logic-board-repair`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/answers/liquid-damage`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/answers/battery-and-screen`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/answers/business-it-support`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/answers/medical-practice-it`, changeFrequency: 'monthly', priority: 0.8 },

    { url: `${base}/macbook-air-repair`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/macbook-pro-repair`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/imac-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/imac-repair/screen`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/imac-repair/ram-upgrade`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/imac-repair/ssd-upgrade`, changeFrequency: 'monthly', priority: 0.85 },

    // MacBook Pro repair sub-pages
    { url: `${base}/macbook-pro-repair/battery`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-pro-repair/screen`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-pro-repair/keyboard`, changeFrequency: 'monthly', priority: 0.8 },

    // Battery replacement (top-level)
    { url: `${base}/battery-replacement`, changeFrequency: 'monthly', priority: 0.85 },

    // MacBook repair hub + sub-pages
    { url: `${base}/macbook-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/macbook-repair/ssd-upgrade`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/ram-upgrade`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/battery`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/screen`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/macbook-repair/keyboard`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/trackpad`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/charging-port`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.8 },
    // §401 corrective 25/05/2026: removed /macbook-repair/liquid-damage + /macbook-repair/logic-board, 
    // both are redirect-only stubs (308 → /liquid-damage, /logic-board-repair). The redirects remain
    // for user-typed/old-backlink URLs but the URLs must not be advertised in sitemap.

    { url: `${base}/macbook-repair/data-recovery`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/macbook-repair/virus-removal`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.8 },

    // Liquid damage sub-pages
    { url: `${base}/liquid-damage/macbook-pro`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/macbook-air`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/iphone`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/ipad`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/liquid-damage/apple-watch`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/liquid-damage/imac`, changeFrequency: 'monthly', priority: 0.7 },

    // Logic board sub-pages
    { url: `${base}/logic-board-repair/macbook-pro`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/logic-board-repair/macbook-air`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/logic-board-repair/imac`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/mac-mini`, changeFrequency: 'monthly', priority: 0.7 },

    // Logic board model-specific pages
    { url: `${base}/logic-board-repair/macbook-pro-m1`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m2`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m3`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m4`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-m5`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-14-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-16-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-pro-13-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m1`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m2`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m3`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m4`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/macbook-air-m5`, changeFrequency: 'monthly', priority: 0.85 },

    // Logic board suburb pages
    { url: `${base}/logic-board-repair/sandton`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/rosebank`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/midrand`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/randburg`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/fourways`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/bryanston`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/kempton-park`, changeFrequency: 'monthly', priority: 0.85 },

    // Screen repair hub
    { url: `${base}/screen-repair`, changeFrequency: 'weekly', priority: 0.95 },

    // Liquid damage model-specific pages
    { url: `${base}/liquid-damage/macbook-pro-m1`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m2`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m3`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m4`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-m5`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-13-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-14-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-pro-16-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m1`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m2`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m3`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m4`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/macbook-air-m5`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/mac-mini`, changeFrequency: 'monthly', priority: 0.85 },

    // Battery replacement model pages
    { url: `${base}/battery-replacement/macbook-pro`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/macbook-air`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/imac`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/iphone`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/mac-mini`, changeFrequency: 'monthly', priority: 0.8 },

    // Battery replacement suburb pages
    { url: `${base}/battery-replacement/sandton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/rosebank`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/fourways`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/bryanston`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/midrand`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/randburg`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/kempton-park`, changeFrequency: 'monthly', priority: 0.8 },

    // Screen repair model pages
    { url: `${base}/screen-repair/macbook-pro`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m1`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m2`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-m3`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-pro-13-inch`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/macbook-air`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/screen-repair/imac`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/iphone`, changeFrequency: 'monthly', priority: 0.85 },

    // Screen repair suburb pages
    { url: `${base}/screen-repair/sandton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/rosebank`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/bryanston`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/fourways`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/midrand`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/randburg`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/kempton-park`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/pretoria`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/centurion`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/morningside`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/rivonia`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/sunninghill`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/paulshof`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/northcliff`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/houghton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/parkhurst`, changeFrequency: 'monthly', priority: 0.8 },

    // iPhone screen repair suburb pages
    { url: `${base}/iphone-repair/screen/sandton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/rosebank`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/fourways`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/bryanston`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/midrand`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/randburg`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/screen/kempton-park`, changeFrequency: 'monthly', priority: 0.8 },

    // Liquid damage suburb pages
    { url: `${base}/liquid-damage/sandton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/rosebank`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/fourways`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/bryanston`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/midrand`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/randburg`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/kempton-park`, changeFrequency: 'monthly', priority: 0.8 },

    // iPhone repair sub-pages
    { url: `${base}/iphone-repair/screen`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/battery`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/iphone-repair/charging`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/iphone-repair/back-glass`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/iphone-repair/camera`, changeFrequency: 'monthly', priority: 0.7 },
    // §401 corrective 25/05/2026: removed /iphone-repair/liquid-damage, redirect-only stub (308 → /liquid-damage/iphone). Redirect retained for old URLs.

    // iPad repair sub-pages
    { url: `${base}/ipad-repair`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/ipad-repair/screen`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/ipad-repair/battery`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/ipad-repair/charging`, changeFrequency: 'monthly', priority: 0.7 },

    // Apple Watch repair
    { url: `${base}/apple-watch-repair`, changeFrequency: 'monthly', priority: 0.8 },


    // Apple accessories repair
    { url: `${base}/accessories-repair`, changeFrequency: 'monthly', priority: 0.7 },

    // Mac Mini repair
    { url: `${base}/mac-mini-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.9 },

    // Business services, sector pages
    { url: `${base}/enterprise`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/sme-support`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/medical-it`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/government`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/jamf-mdm`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/apple-specialist`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/it-support`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/managed-services/investec`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/managed-services/unifi-networking`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/managed-services/wealth-management`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/apple-support/medical-practices`, changeFrequency: 'monthly', priority: 0.85 },
    // §401 corrective 25/05/2026: removed /apple-support/business + /apple-support/enterprise, 
    // both are redirect-only stubs (308 → /managed-services, /jamf-mdm). Redirects retained.


    // §401 corrective 25/05/2026: removed /ipad-repair/liquid-damage, redirect-only stub (308 → /liquid-damage/ipad). Redirect retained.

    // Assessment Process, transparent pricing page
    { url: `${base}/no-fix-no-fee`, changeFrequency: 'weekly', priority: 0.95 },

    // Editorial policy (E-E-A-T trust page; indexable, was missing from sitemap, F6 27/07/2026)
    { url: `${base}/editorial-policy`, changeFrequency: 'monthly', priority: 0.5 },

    // Author pages
    { url: `${base}/author/courtney-bentley`, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/author/mary`, changeFrequency: 'monthly', priority: 0.5 },

    // Core pages
    { url: `${base}/about`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/services`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/contact`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/privacy`, changeFrequency: 'yearly', priority: 0.4 },
    { url: `${base}/terms`, changeFrequency: 'yearly', priority: 0.4 },

    // Blog
    { url: `${base}/blog`, changeFrequency: 'weekly', priority: 0.6 },
    // §346/§402 reconciliation 10/06/2026, live-200 posts that were absent from sitemap (3-way slug set-diff vs blog data)
    { url: `${base}/blog/liquid-damage-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/no-power-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/how-to-backup-mac-that-wont-turn-on-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/mac-repair-rivonia-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-liquid-damage-repair-bryanston`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/managed-it-medical-practice-morningside-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-load-shedding-damage`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/why-rice-does-not-work`, changeFrequency: 'yearly', priority: 0.6 },
    { url: `${base}/blog/jamf-mdm-guide-south-africa`, changeFrequency: 'yearly', priority: 0.6 },
    { url: `${base}/blog/macbook-running-slow`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-wont-connect-wifi`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/apple-id-locked-out`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/how-to-speed-up-mac-free`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/mac-not-turning-on-checklist`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-logic-board-repair-cost-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-battery-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-screen-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.8 },
    { url: `${base}/blog/macbook-wont-charge-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-overheating-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-keyboard-not-working`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/iphone-screen-repair-cost-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.75 },
    { url: `${base}/blog/mac-data-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-pro-m1-m2-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.75 },
    { url: `${base}/blog/macbook-trackpad-not-clicking`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.65 },
    { url: `${base}/blog/apple-watch-screen-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/ipad-screen-repair-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/mac-mini-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/how-to-check-macbook-battery-health`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-black-screen-on-startup`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/when-to-replace-vs-repair-macbook`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-ssd-upgrade-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/imac-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-speaker-not-working`, changeFrequency: 'yearly', priority: 0.65 },
    { url: `${base}/blog/airpods-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-wifi-keeps-disconnecting`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/blog/macbook-logic-board-symptoms-johannesburg`, changeFrequency: 'yearly', priority: 0.75 },

    // Auto-generated suburb pages, overnight batch
    { url: `${base}/logic-board-repair/pretoria`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/pretoria`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/pretoria`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/pretoria`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/centurion`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/centurion`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/centurion`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/centurion`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/morningside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/morningside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/morningside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/morningside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/rivonia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/rivonia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/rivonia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/rivonia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/sunninghill`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/sunninghill`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/sunninghill`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/sunninghill`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/paulshof`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/paulshof`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/paulshof`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/paulshof`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/northcliff`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/northcliff`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/northcliff`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/northcliff`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/houghton`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/houghton`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/houghton`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/houghton`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/parkhurst`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/parkhurst`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/parkhurst`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/iphone-repair/screen/parkhurst`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/parktown-north`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/parktown-north`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/parktown-north`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/parktown-north`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/greenside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/greenside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/greenside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/greenside`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/craighall`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/craighall`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/craighall`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/craighall`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/linden`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/linden`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/linden`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/linden`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/emmarentia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/emmarentia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/emmarentia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/emmarentia`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/logic-board-repair/melville`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/melville`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/melville`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/melville`, changeFrequency: 'monthly', priority: 0.85 },

        { url: `${base}/blog/macbook-pro-m2-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-data-recovery`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-cost-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-not-turning-on-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-not-charging-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-mac-battery-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-screen-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-charging-port-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-trackpad-not-clicking-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },

    // Complete service/suburb/model pages, auto-synced 30/03/2026
    { url: `${base}/battery-replacement/macbook-pro-13-inch`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-14-inch`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m1`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m2`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-m3`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/mac-mini`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m1`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m2`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-air-m3`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-pro-14-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/screen-repair/macbook-pro-16-inch`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/battery-replacement/macbook-air-m1`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-air-m2`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-air-m3`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/macbook-pro-16-inch`, changeFrequency: 'monthly', priority: 0.8 },

    // Troubleshooting guides (HowTo schema, featured snippet targets)
    { url: `${base}/guides`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/guides/macbook-not-turning-on`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-water-damage-what-to-do`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-not-charging`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/macbook-overheating-fix`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/macbook-screen-flickering`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-check-macbook-battery-health`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-recover-data-from-dead-macbook`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/macbook-running-slow`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/jamf-mdm-medical-practice-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-dainfern-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-law-firm-apple-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },

    // §194/§223 New suburb pages, TIER 1 ≤20km and TIER 2 20-60km from Hyde Park
    { url: `${base}/logic-board-repair/melrose`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/melrose`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/melrose`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/melrose`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/illovo`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/illovo`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/illovo`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/illovo`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/woodmead`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/woodmead`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/woodmead`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/woodmead`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/kyalami`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/kyalami`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/kyalami`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/kyalami`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/logic-board-repair/edenvale`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/edenvale`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/edenvale`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/edenvale`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/bedfordview`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/bedfordview`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/bedfordview`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/bedfordview`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/roodepoort`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/roodepoort`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/roodepoort`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/roodepoort`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/boksburg`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/boksburg`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/boksburg`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/boksburg`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/benoni`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/benoni`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/benoni`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/benoni`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/alberton`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/alberton`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/alberton`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/alberton`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/germiston`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/liquid-damage/germiston`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/screen-repair/germiston`, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/battery-replacement/germiston`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/logic-board-repair/randpark-ridge`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/liquid-damage/randpark-ridge`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/screen-repair/randpark-ridge`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/battery-replacement/randpark-ridge`, changeFrequency: 'monthly', priority: 0.75 },
        { url: `${base}/blog/apple-vs-third-party-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fan-noise-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-wifi-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-swollen-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-not-turning-on-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-swollen-replacement-sandton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-popia-it-provider-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-usb-c-port-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-it-provider-agreement-medical-practice`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-speaker-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-touch-id-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-certified-repair-hyde-park`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/corporate-apple-fleet-management-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m3-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-midrand`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-hinge-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-kernel-panic-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-it-security-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-sandton-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-max-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-flickering-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-pro-sandton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-draining-fast-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-black-screen-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-running-slow-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-not-turning-on-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-camera-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-indicator-check-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-m3-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-repair-bryanston`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-startup-disk-full-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-repair-vs-replacement-guide-johannesburg`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/investec-sandton-apple-support`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-parkhurst`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-to-diagnose-macbook-fault-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-migration-assistant-guide-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-support-financial-services-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-support-small-business-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-backup-time-machine-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-security-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-preventive-maintenance-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/hpcsa-records-mac-backup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-clean-install-macos-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-cooling-pad-worth-it-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/goodx-mac-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/carepoint-mac-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-virus-removal-johannesburg`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-emr-mac-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/second-hand-mac-check-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/carepoint-macbook-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-fusion-drive-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-backlight-ic-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-display-cable-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pmic-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-managed-it-morningside`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-battery-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-medical-practice-gauteng`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-managed-it-sandton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-screen-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-battery-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-sandton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-charging-ic-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-midrand`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-melrose`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-ram-upgrade-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-trackpad-ribbon-cable-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-business-manager-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-bryanston`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-houghton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-pro-2019-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-rosebank`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-firmware-restore-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-wifi-card-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/corporate-mac-onboarding-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-rosebank`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-centurion`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-fourways`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-midrand`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-rivonia`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-rosebank`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-morningside`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-clean-install-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/tim-cook-steps-down-john-ternus-apple-ceo-south-africa`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/who-is-john-ternus-apple-ceo-engineer`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-ceo-change-johannesburg-business-fleet`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-morningside-medical`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/milpark-hospital-macbook-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/netcare-rosebank-apple-it-support`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/sunninghill-hospital-mac-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/same-day-macbook-repair-doctors-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-midstream-estate`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/jamf-implementation-sandton-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/marketing-agency-imac-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/tech-startup-jamf-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fleet-management-sandton`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-macbook-encryption-sme-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/charlotte-maxeke-hospital-apple-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/life-fourways-hospital-apple-it`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-liquid-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-bryanston-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-screen-repair-rosebank`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-logic-board-failure-signs`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-much-macbook-repair-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-pro-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-hdmi-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-short-circuit-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-2020-intel-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-repair-prices-johannesburg-2026`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-price-guide-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-repair-cost-2026`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-replacement-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/repair-vs-replace-macbook-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-logic-board-repair-johannesburg-2026`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-air-logic-board-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-pro-m1-logic-board-fault-symptoms`, changeFrequency: 'yearly', priority: 0.8 },
        { url: `${base}/blog/logic-board-repair-vs-replacement-macbook`, changeFrequency: 'yearly', priority: 0.8 },
        { url: `${base}/blog/macbook-pro-14-inch-logic-board-repair`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-pro-16-inch-logic-board-johannesburg`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-air-m2-logic-board-sandton`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-logic-board-repair-sandton-rosebank`, changeFrequency: 'monthly', priority: 0.85 },
        { url: `${base}/blog/macbook-repair-glenhazel-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/ipad-repair-norwood-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/macbook-air-repair-victory-park-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/macbook-pro-repair-waverley-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/apple-watch-repair-johannesburg-northern-suburbs`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/managed-it-services-jewish-schools-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/mac-repair-sandringham-sydenham-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/macbook-repair-highlands-north-johannesburg`, changeFrequency: 'monthly', priority: 0.8 },
        { url: `${base}/blog/apple-watch-repair-glenhazel-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-watch-repair-sandringham-savoy-estate`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-repair-highlands-north-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-repair-king-david-victory-park-families`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-yeshiva-college-glenhazel`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-repair-savoy-estate-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-king-david-linksfield-parents`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-support-king-david-schools-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-first-30-minutes-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-recovery-protocol-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-repair-vs-upgrade-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-cost-process-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-medical-practices-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-it-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-compliant-it-support-doctors-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/sme-it-support-johannesburg-apple`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-business-manager-setup-johannesburg-sme`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-fleet-management-law-firms-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-pro-m4-screen-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-15-pro-water-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-warranty-johannesburg-explained`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m3-keyboard-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-data-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-2024-display-flickering-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-mini-m4-pro-thermal-throttling-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m4-battery-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-trackpad-not-clicking-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-pro-m4-screen-burn-in-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-15-pro-face-id-not-working-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-mini-server-vs-cloud-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-stuck-key-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/airpods-pro-2-one-side-quiet-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-watch-series-10-not-charging-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intune-vs-jamf-medical-practice-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fan-running-constantly-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-max-purchase-guide-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/office-network-wifi-7-upgrade-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/sme-it-disaster-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/vision-pro-light-seal-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-id-locked-recovery-johannesburg`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/final-cut-pro-render-slow-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/icloud-photos-stuck-uploading-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/icloud-shared-photo-library-team-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-pro-cpu-overload-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-port-not-charging-usbc-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-image-retention-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/safari-keychain-corruption-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-pencil-not-pairing-ipad-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/backup-to-synology-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/home-office-mac-network-storage-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-screen-pink-tint-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macos-sequoia-app-compatibility-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-imaging-workstation-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/office-365-migration-apple-fleet-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/sme-cybershield-bundle-explainer-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/dainfern-apple-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/investec-client-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-mini-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-spilled-water-logic-board-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-apple-sme-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-managed-it-sandton-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-pro-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-warranty-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-while-you-wait-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-shack-alternative-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-apple-microsoft-unifi-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-law-firm-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-medical-practice-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-wealth-manager-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-accountants-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-apple-mac-businesses-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-law-firms-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-medical-practices-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-morningside-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-accountant-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-stack-sme-johannesburg-all-in-one`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/microsoft-365-apple-managed-it-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-managed-it-services-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/istore-business-m365-premium-vs-za-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/istore-business-pricing-vs-za-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/jamf-mdm-alternative-small-business-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-managed-it-services-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-architects-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-creative-agencies-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-with-unifi-networking-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-reseller-alternative-managed-it-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-store-alternative-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/istore-business-alternative-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/istore-repair-alternative-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/hnw-estate-cctv-unifi-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/managed-it-services-for-small-businesses-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-access-door-control-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-business-networking-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-dream-machine-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-networking-business-johannesburg-installation`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-protect-cameras-johannesburg-business`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wealth-manager-unifi-networking-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-installation-expert-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-access-door-control-business-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-dream-machine-pro-business-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-protect-surveillance-business-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-wifi-6-access-point-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-cloud-gateway-ultra-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-dream-machine-pro-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-dream-machine-se-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-installer-johannesburg-business`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-troubleshooting-expert-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-access-point-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-guest-network-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-poe-switch-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-q-a-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-switch-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-u6-pro-access-point-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-u7-pro-access-point-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-vlan-segmentation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-access-door-control-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-configuration-backup-service-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-network-monitoring-service-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-protect-cameras-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-remote-site-vpn-setup-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-talk-voip-installation-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-wifi-7-upgrade-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-wifi-calling-iphone-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-much-does-unifi-installation-cost-in-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-consultant-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/unifi-managed-service-provider-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-data-recovery-m1-m2-m3-m4-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-data-recovery-t2-chip-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-liquid-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-m3-logic-board-liquid-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-m3-logic-board-data-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-m3-logic-board-failure-diagnostics-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-m3-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-m3-no-power-logic-board-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-spilled-coffee-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-spilled-wine-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-data-recovery-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-consultants-network-south-africa-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/exchange-online-to-m365-business-premium-migration-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/hnw-apple-vision-pro-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-apple-watch-clinical-use-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/microsoft-365-business-premium-south-africa-pricing-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wont-turn-on-northcliff`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/water-damage-repair-parkhurst`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-repair-parkhurst`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-practice-liquid-damage-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wealth-manager-data-recovery-urgent-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wealth-manager-liquid-damage-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-authorised-vs-independent-repair-johannesburg`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/apple-background-security-update-safari-mac-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/apple-device-management-law-firms-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-dead-macbook-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/how-to-save-water-damaged-macbook-air`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/imac-logic-board-repair-johannesburg-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/ipad-screen-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/iphone-fold-is-on-track-to-launch-this-september-per-ma-south-africa-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/iphone-will-still-exist-50-years-from-now-says-apple-an-south-africa-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-air-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-macbook-data-recovery-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-cost-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/m5-macbook-air-review-incremental-update-but-the-best-b-south-africa-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/mac-repair-vs-apple-store-johannesburg-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m2-water-damage-recovery-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-health-below-80-percent`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-repair-cost-south-africa-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-warning-signs-checklist`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-logic-board-repair-vs-replacement`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-overheating-fix-johannesburg-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-coffee-spill-emergency-response`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-logic-board-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-logic-board-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-no-power-repair-hyde-park`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-rain-damage-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-screen-replacement-cost-johannesburg-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-ssd-upgrade-johannesburg-worth-it-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-thunderbolt-port-repair-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-first-aid`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-repair-cost-2026`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/signs-macbook-has-liquid-damage`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/signs-of-water-damage-macbook`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/spilled-water-macbook-air-johannesburg`, changeFrequency: 'monthly', priority: 0.7 },
        { url: `${base}/blog/imac-vertical-lines-on-screen-gpu`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-flexgate-display-cable-failure`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-kernel-panic-causes-and-fixes`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-liquid-damage-first-24-hours`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-wont-turn-on-diagnosis`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-stage-light-effect-explained`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-swollen-battery-warning-signs`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-t2-security-chip-failure-symptoms`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-usb-c-not-charging-troubleshooting`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-water-damage-corrosion-repair-process`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/no-power-vs-no-display-macbook-difference`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/thunderbolt-port-not-working-macbook`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-backlight-failure-dim-screen`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fan-running-loud-causes`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-not-detecting-ssd-data-recovery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-shuts-down-randomly-causes`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-three-beeps-on-startup-ram`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/spilled-coffee-on-macbook-what-to-do`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-trackpad-not-clicking-swollen-battery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macos-recovery-mode-not-working`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-from-dead-macbook`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ipad-wont-charge-troubleshooting`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-water-damage-first-steps`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/iphone-wont-charge-port-clean-vs-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-vs-replacement-cost`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-mini-wont-power-on-diagnosis`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-battery-service-recommended-meaning`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-camera-not-working-troubleshooting`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-display-flickering-causes`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-keys-not-working`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-no-sound-speaker-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-overheating-thermal-shutdown`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-soldered-ssd-storage-explained`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-startup-chime-no-display`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-wifi-bluetooth-not-working-board`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/why-apple-declines-liquid-damage-repair`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/jamf-pro-vs-intune-mac-management`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-stuck-on-apple-logo`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-thermal-paste-replacement`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/apple-logic-board-repair-johannesburg-cost`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/first-30-minutes-liquid-spill-macbook-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/how-much-to-fix-macbook-logic-board-south-africa-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-black-screen-no-backlight-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-coffee-spilled-won-t-turn-on-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-condensation-damage-logic-board-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-screen-repair-johannesburg-cost`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/popia-compliance-medical-practice-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/bace-discovery-integration-apple-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/goodx-support-apple-mac-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/healthbridge-mac-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-warranty-sa-out-of-warranty-repair-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/medical-aid-mac-device-support-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/vericlaim-apple-mac-integration-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/gpu-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/gpu-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-wont-turn-on`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/liquid-damage-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/logic-board-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-data-recovery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-no-power-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/mac-studio-wont-turn-on`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-data-recovery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-no-power-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-16-inch-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-data-recovery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m1-no-power-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/no-power-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/water-damage-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/water-damage-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wont-turn-on-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wont-turn-on-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/no-power-repair-how-much-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/water-damage-repair-how-much-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wont-turn-on-how-much-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/charging-port-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/data-recovery-specialist-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/gpu-repair-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/gpu-repair-specialist-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-battery-replacement`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-charging-port-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-keyboard-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-macbook-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-ram-upgrade`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-screen-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-ssd-upgrade`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/keyboard-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-repair-vs-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ram-upgrade-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ram-upgrade-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ram-upgrade-vs-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/screen-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/screen-repair-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/screen-repair-vs-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/screen-repair-how-much-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-how-much-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-vs-replacement-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/battery-replacement-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/charging-port-repair-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/battery-replacement-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-27-inch-no-power-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-27-inch-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-27-inch-wont-turn-on`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/imac-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/intel-macbook-pro-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m3-logic-board-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-air-m3-wont-turn-on`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-13-inch-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-data-recovery`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-14-inch-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m2-wont-turn-on`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-data-recovery`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m3-water-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-charging-port-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-gpu-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-keyboard-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-liquid-damage-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-macbook-repair`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-ram-upgrade`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-pro-m4-ssd-upgrade`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/screen-repair-near-me-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/keyboard-repair-specialist-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/trackpad-repair-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/trackpad-repair-specialist-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/charging-port-repair-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/keyboard-repair-same-day-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/ssd-upgrade-specialist-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/wont-turn-on-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/trackpad-repair-cost-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/water-damage-repair-price-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-fan-always-loud-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keeps-restarting-fix-johannesburg`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/flexgate-and-display-cable-faults-on-macbooks-explained`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-keyboard-keys-repeating-or-dead-what-it-means`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/macbook-runs-hot-and-fans-loud-what-we-check-first`, changeFrequency: 'yearly', priority: 0.7 },
        { url: `${base}/blog/what-a-macbook-liquid-damage-assessment-involves`, changeFrequency: 'yearly', priority: 0.7 },
    { url: `${base}/suspected-hacked-apple-device`, lastModified: new Date('2026-09-21T06:30:14Z'), changeFrequency: 'monthly', priority: 0.7 }, // §718 auto-added 2026-09-18
  ];
}
