#!/usr/bin/env python3
"""
auto-blog-insert.py — ZA Support Overnight Blog Auto-Inserter
Reads Haiku-generated markdown drafts from ~/Desktop/Claude/Blog/
Inserts them into blog/[slug]/page.tsx posts map + sitemap + faqSchemas.
Runs after blog_research_draft task in overnight batch.
Cost: $0.00 (no API calls — pure file manipulation).
"""

import os
import re
import sys
import subprocess
import json
from pathlib import Path
from datetime import date, datetime

# §343/§377 — strip body-content leaks (```json / ```markdown wrapper / <script> /
# schema headings / Word-count + Internal-links metadata) BEFORE a post can land.
# The FAQ schema is separately extracted into faqSchemas / auto-generated by the
# template, so removing the body copy loses nothing. This is the insertion-path
# guard so a broken post can never be inserted again (the recurrence root cause).
sys.path.insert(0, str(Path(__file__).parent))
try:
    from blog_content_sanitiser import sanitise as _sanitise_body
except Exception:
    def _sanitise_body(c, escaped=False):  # fail-open is unacceptable; fail-loud
        raise RuntimeError("blog_content_sanitiser.sanitise unavailable — refusing to insert un-sanitised content (§343)")

# §547 — em/en-dash normalisation at the INSERTION path. The body is dash-stripped
# inside _sanitise_body, but title / excerpt / FAQ text are extracted separately and
# bypassed normalisation (root cause 27/06/2026: 8 em-dashes landed in titles+listing
# excerpts → pre-commit §547 gate rejected the commit → _commit_with_heal's sanitiser
# only cleans [slug]/page.tsx body, never blog/page.tsx listing → posts stranded
# uncommitted every run). Normalise at the extract chokepoint so EVERY text field
# (Record title/excerpt, listing entry, FAQ schema) is dash-clean before it lands.
try:
    from dash_normalizer import normalize_dashes as _normalize_dashes
except Exception:
    def _normalize_dashes(c):  # fail-loud — never let a raw glyph reach production (§547)
        raise RuntimeError("dash_normalizer.normalize_dashes unavailable — refusing to insert un-normalised content (§547)")

# §489 PRE-INSERT PRICE FILTER (29/06/2026): Haiku disobeys the prompt price-guard and emits
# invented Rand prices, which the pre-commit §489 gate then rejects -> the whole commit strands
# (recurring 23->35 stranded-post mess). Fix per advisor: do NOT auto-scrub prices (no correct
# transform — pricing is human-gated); instead REFUSE to insert a draft that carries unconfirmed
# prices. Nothing bad enters the file -> no strand, gate stays the protective wall. Reuses the
# §489 gate's own offenders() as SoT (§354 no-fork).
try:
    import importlib.util as _ilu
    _spec = _ilu.spec_from_file_location("_price_gate", str(Path(__file__).parent / "check-blog-price-allowlist.py"))
    _pg = _ilu.module_from_spec(_spec); _spec.loader.exec_module(_pg)
    def _unconfirmed_prices(text):
        return _pg.offenders(text)   # [] if clean, else [(token, ctx), ...]
except Exception:
    def _unconfirmed_prices(text):   # fail-loud — never silently insert unverified prices (§489/§374)
        raise RuntimeError("check-blog-price-allowlist.offenders unavailable — refusing to insert price-unverified content (§489)")

WEBSITE_DIR = Path(__file__).parent.parent
BLOG_PAGE = WEBSITE_DIR / "src" / "app" / "blog" / "[slug]" / "page.tsx"
BLOG_LISTING = WEBSITE_DIR / "src" / "app" / "blog" / "page.tsx"
SITEMAP = WEBSITE_DIR / "src" / "app" / "sitemap.ts"
BLOG_DRAFTS_DIR = Path.home() / "Desktop" / "Claude" / "Blog"
INSERTED_LOG = BLOG_DRAFTS_DIR / ".inserted.json"

# §277: honour BLOG_INSERT_DATE override (format "DD Month YYYY") for backfill runs
_override = os.environ.get("BLOG_INSERT_DATE", "").strip()
if _override:
    _d = datetime.strptime(_override, "%d %B %Y").date()
    TODAY = _d.strftime("%d %B %Y")
    TODAY_DISPLAY = _d.strftime("%d/%m/%Y")
    TODAY_SLUG = _d.strftime("%d%m%Y")
else:
    TODAY = date.today().strftime("%d %B %Y")
    TODAY_DISPLAY = date.today().strftime("%d/%m/%Y")
    TODAY_SLUG = date.today().strftime("%d%m%Y")


def load_inserted() -> set:
    if INSERTED_LOG.exists():
        return set(json.loads(INSERTED_LOG.read_text()))
    return set()


def save_inserted(slugs: set):
    INSERTED_LOG.write_text(json.dumps(list(slugs), indent=2))


def slug_from_filename(fname: str) -> str:
    """draft-macbook-wont-charge-johannesburg-22032026.md → macbook-wont-charge-johannesburg"""
    name = fname.replace("draft-", "").replace(".md", "")
    # Strip any 8-digit date suffix (DDMMYYYY) from the end
    name = re.sub(r'-\d{8}$', '', name)
    return name


def extract_title(content: str) -> str:
    """Extract H1 title from markdown. §547: dash-normalised at source so every
    consumer (Record entry + listing entry) gets a dash-clean title."""
    m = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    return _normalize_dashes(m.group(1).strip()) if m else "Untitled"


def extract_excerpt(content: str) -> str:
    """Extract first non-heading paragraph as excerpt."""
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if line and not line.startswith('#') and not line.startswith('```') and len(line) > 40:
            return _normalize_dashes(line[:200].rstrip('.')+'.')  # §547 dash-clean at source
    return "ZA Support Apple repair specialists in Hyde Park, Johannesburg."


def extract_faqs_from_content(content: str) -> list[dict]:
    """
    Extract FAQ JSON-LD block from blog post content if present.
    Falls back to generating 3 generic FAQs from the slug topic.
    """
    # Try to find JSON-LD FAQ block in the markdown
    faq_match = re.search(r'```(?:json)?\s*(\{[^`]*"@type"\s*:\s*"FAQPage"[^`]*\})\s*```', content, re.DOTALL)
    if faq_match:
        try:
            schema = json.loads(faq_match.group(1))
            entities = schema.get("mainEntity", [])
            return [
                {
                    "question": e.get("name", ""),
                    "answer": e.get("acceptedAnswer", {}).get("text", ""),
                }
                for e in entities[:6]
                if e.get("name")
            ]
        except json.JSONDecodeError:
            pass

    # Extract Q&A pairs from ### headings followed by paragraph text
    faqs = []
    lines = content.split('\n')
    i = 0
    while i < len(lines) and len(faqs) < 6:
        line = lines[i].strip()
        if line.startswith('###') and '?' in line:
            q = line.lstrip('#').strip()
            # Collect answer (next non-empty lines until next heading)
            answer_lines = []
            i += 1
            while i < len(lines):
                l = lines[i].strip()
                if l.startswith('#') or l.startswith('---'):
                    break
                if l:
                    answer_lines.append(l)
                i += 1
            if answer_lines:
                faqs.append({"question": q, "answer": " ".join(answer_lines[:3])})
            continue
        i += 1

    return faqs[:6] if faqs else []


def escape_ts(text: str) -> str:
    """Escape text for TypeScript template literal."""
    return text.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')


def read_time(content: str) -> str:
    words = len(content.split())
    mins = max(4, words // 200)
    return f"{mins} min read"


# §529 doorway detection — Gauteng suburb tokens (§169) that, when permuted with a
# service term into a /blog slug, create a doorway page. Named-entity tokens (§194) are
# high-value and exempt (kept live in the 10/06 prune).
# Static floor (suburbs that may not yet have a /service dir). The live set below
# UNIONS this with the real /logic-board-repair/ service dirs so the guard can never
# drift out of sync (§529 root-cause 11/06/2026: static-only set silently missed
# melville/craighall/emmarentia/greenside/linden/parktown-north → doorway posts slipped through).
_DOORWAY_SUBURBS_FLOOR = {
    'sandton', 'rosebank', 'bryanston', 'fourways', 'morningside', 'rivonia', 'houghton',
    'melrose', 'illovo', 'parkhurst', 'northcliff', 'randburg', 'sunninghill', 'paulshof',
    'woodmead', 'kyalami', 'edenvale', 'bedfordview', 'midrand', 'kempton-park', 'centurion',
    'pretoria', 'roodepoort', 'boksburg', 'benoni', 'alberton', 'germiston', 'randpark-ridge',
}
# device/model dirs under /logic-board-repair/ that are NOT suburbs (must not be flagged)
_NON_SUBURB_DIRS = {'imac', 'mac-mini', 'mac-studio', 'mac-pro'}

def _service_suburbs():
    """Derive the live suburb set from the /logic-board-repair/ service dirs (the SoT).
    Excludes model/device dirs and files. Fails safe to the static floor on any error."""
    import os
    base = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', 'src', 'app', 'logic-board-repair')
    out = set()
    try:
        for d in os.listdir(base):
            if not os.path.isdir(os.path.join(base, d)):
                continue
            if d.startswith('macbook') or d in _NON_SUBURB_DIRS:
                continue  # model/device dir, not a suburb
            out.add(d)
    except OSError:
        pass
    return out

DOORWAY_SUBURBS = _DOORWAY_SUBURBS_FLOOR | _service_suburbs()
NAMED_ENTITY_TOKENS = {
    'investec', 'hospital', 'clinic', 'jamf', 'netcare', 'medical', 'wealth', 'law',
    'practice', 'practices', 'mediclinic', 'specialist',
}


def is_doorway_slug(slug: str) -> bool:
    """§529: True if slug is a service×suburb permutation with no high-value named-entity
    token. These belong on /service/<suburb> pages, not /blog — block at insert time."""
    s = slug.lower()
    if any(tok in s for tok in NAMED_ENTITY_TOKENS):
        return False  # §194 high-value — keep
    return any(re.search(rf'(^|-){sub}(-|$)', s) for sub in DOORWAY_SUBURBS)


def category_from_slug(slug: str) -> str:
    """Infer category from slug."""
    if any(k in slug for k in ['cost', 'price', 'how-much']):
        return 'Pricing'
    if any(k in slug for k in ['how-to', 'check', 'guide']):
        return 'How-To'
    if any(k in slug for k in ['repair', 'logic-board', 'screen', 'battery']):
        return 'Repairs'
    if any(k in slug for k in ['wont', 'not-working', 'disconnecting', 'overheating', 'symptoms']):
        return 'Troubleshooting'
    return 'Repairs'


def build_post_entry(slug: str, content: str) -> str:
    title = escape_ts(extract_title(content))
    excerpt = escape_ts(extract_excerpt(content))
    rt = read_time(content)
    cat = category_from_slug(slug)
    # §343/§377 insertion-path guard: sanitise body BEFORE escaping. FAQ schema is
    # extracted separately (extract_faqs_from_content) / auto-generated by the
    # template from the markdown FAQ section, so stripping the body copy is lossless.
    body = escape_ts(_sanitise_body(content))

    # §230: Author ALWAYS Courtney Bentley — never 'ZA Support', 'David Bentley', or anonymous
    author_slug = 'courtney-bentley'
    return f"""  '{slug}': {{
    slug: '{slug}',
    title: `{title}`,
    excerpt: `{excerpt}`,
    date: '{TODAY}',
    category: '{cat}',
    readTime: '{rt}',
    author: '{author_slug}',
    content: `{body}`,
  }},"""


def build_faq_schema_entry(slug: str, faqs: list[dict]) -> str:
    if not faqs:
        return ""

    entities = []
    for faq in faqs:
        q = escape_ts(_normalize_dashes(faq["question"]))  # §547 dash-clean
        a = escape_ts(_normalize_dashes(faq["answer"]))    # §547 dash-clean
        entities.append(
            f"      {{ '@type': 'Question', name: `{q}`, acceptedAnswer: {{ '@type': 'Answer', text: `{a}` }} }},"
        )

    entities_str = "\n".join(entities)
    return f"""  '{slug}': {{
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
{entities_str}
    ],
  }},"""


def insert_into_blog_page(slug: str, post_entry: str, faq_entry: str) -> bool:
    """Insert post entry and FAQ schema into blog/[slug]/page.tsx."""
    content = BLOG_PAGE.read_text()

    # Check if already inserted
    if f"'{slug}':" in content:
        print(f"  SKIP: '{slug}' already in blog page")
        return False

    # Insert post into POSTS object
    posts_marker = "// END_POSTS"
    if posts_marker not in content:
        # Fallback: find the closing }; of the const posts = { ... }; block.
        # The block ends with "};\n\nexport async function generateStaticParams"
        posts_close = "\n};\n\nexport async function generateStaticParams"
        if posts_close not in content:
            # Last-resort: insert before generateStaticParams
            posts_close_alt = "\nexport async function generateStaticParams"
            if posts_close_alt not in content:
                print(f"  ERROR: cannot find posts insertion point for {slug}")
                return False
            content = content.replace(
                posts_close_alt,
                f"\n{post_entry}\n}};\n\nexport async function generateStaticParams"
            )
        else:
            content = content.replace(
                posts_close,
                f"\n{post_entry}{posts_close}"
            )
    else:
        content = content.replace(
            posts_marker,
            f"{post_entry}\n  {posts_marker}"
        )

    # Insert FAQ schema if present
    if faq_entry:
        faq_marker = "// END_FAQ_SCHEMAS"
        if faq_marker not in content:
            # Fallback: find faqSchemas closing }; before export default
            import re as _re
            # Find the faqSchemas block end — look for last entry in it
            faq_close = "\n  };\n\n  if (faqSchemas"
            if faq_close in content:
                content = content.replace(
                    faq_close,
                    f"\n{faq_entry}{faq_close}"
                )
            else:
                faq_marker_alt = "} as Record<string, object>"
                if faq_marker_alt in content:
                    content = content.replace(
                        faq_marker_alt,
                        f"{faq_entry}\n{faq_marker_alt}"
                    )
        else:
            content = content.replace(
                faq_marker,
                f"{faq_entry}\n  {faq_marker}"
            )

    BLOG_PAGE.write_text(content)
    return True


def insert_listing_entry(slug: str, title: str, excerpt: str, category: str, read_time_str: str):
    """Insert post into the blog listing page (blog/page.tsx) so it appears on /blog."""
    if not BLOG_LISTING.exists():
        print(f"  WARN: Blog listing page not found — post won't appear on /blog")
        return

    content = BLOG_LISTING.read_text()

    if f"'{slug}'" in content:
        return  # Already in listing

    # Escape for JS single-quote strings
    safe_title = title.replace("'", "\\'").replace('"', '\\"')
    safe_excerpt = excerpt.replace("'", "\\'").replace('"', '\\"')

    # Standardise to 'DD Month YYYY' format (matches blog detail page)
    entry = (
        f"  {{ slug: '{slug}', title: '{safe_title}', "
        f"excerpt: '{safe_excerpt}', "
        f"date: '{TODAY}', category: '{category}', "
        f"readTime: '{read_time_str}' }},"
    )

    # Insert at the TOP of the posts array (newest first) — right after "const posts = ["
    marker = "const posts = ["
    if marker in content:
        content = content.replace(marker, f"{marker}\n{entry}")
        BLOG_LISTING.write_text(content)


def insert_sitemap_entry(slug: str):
    content = SITEMAP.read_text()
    entry = f"    {{ url: `${{base}}/blog/{slug}`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 }},"

    if f"/blog/{slug}" in content:
        return  # Already in sitemap

    marker = "  ];\n}"
    if marker in content:
        content = content.replace(marker, f"    {entry}\n{marker}")
        SITEMAP.write_text(content)


def main():
    if not BLOG_DRAFTS_DIR.exists():
        print(f"Blog drafts dir not found: {BLOG_DRAFTS_DIR}")
        return 0

    drafts = list(BLOG_DRAFTS_DIR.glob(f"draft-*-{TODAY_SLUG}.md"))
    if not drafts:
        # Also check for any uninserted drafts from recent days
        drafts = list(BLOG_DRAFTS_DIR.glob("draft-*.md"))

    if not drafts:
        print("No blog drafts found to insert.")
        return 0

    inserted = load_inserted()
    newly_inserted = []

    print(f"Found {len(drafts)} drafts. Already inserted: {len(inserted)}")
    print("=" * 60)

    for draft_path in sorted(drafts):
        slug = slug_from_filename(draft_path.name)

        if slug in inserted:
            print(f"  SKIP (already inserted): {slug}")
            continue

        # §529 DATA-DRIVEN DOORWAY GUARD (root-cause fix for recurring doorway posts):
        # a /blog slug that is a service×suburb permutation belongs on a /service/<suburb>
        # page, NOT in the blog — it dilutes the cluster and gets pruned/301'd anyway.
        # Block it at insert time UNLESS it carries a high-value named-entity token (§194).
        if is_doorway_slug(slug):
            print(f"  SKIP (§529 doorway suburb-permutation — belongs on /service, not /blog): {slug}")
            continue

        # iCloud advisory locks can raise EDEADLK (errno 11) on read_text().
        # Retry once after forcing a download, then skip this draft if still locked.
        try:
            content = draft_path.read_text()
        except OSError as e:
            if e.errno == 11:
                subprocess.run(["brctl", "download", str(draft_path)], check=False)
                try:
                    content = draft_path.read_text()
                except OSError as e2:
                    print(f"  SKIP (iCloud lock EDEADLK): {draft_path.name} — {e2}")
                    continue
            else:
                raise
        word_count = len(content.split())

        # §229 tiered word count validation
        # Repair/competitive keywords need 1500+, informational 1200+, troubleshooting 800+
        cat = category_from_slug(slug)
        min_words = 800  # base minimum for all posts
        if cat == 'Repairs':
            min_words = 800  # accept 800 for now; 1500+ is target but Haiku caps output
        if word_count < min_words:
            print(f"  SKIP (too short): {slug} ({word_count} words, min {min_words} for {cat})")
            continue

        # §489 PRE-INSERT PRICE FILTER: refuse drafts with unconfirmed/invented Rand prices.
        # Never insert -> never strand. Escalate so the skip is loud, not silent (§621/§313/§374).
        _bad = _unconfirmed_prices(content)
        if _bad:
            toks = ", ".join(sorted({t for t, _ in _bad}))
            print(f"  SKIP (§489 invented price): {slug} — {len(_bad)} unconfirmed Rand figure(s): {toks}")
            try:
                import json as _json, time as _time
                with open(Path.home() / ".za-blog-price-reject.jsonl", "a") as _f:
                    _f.write(_json.dumps({"ts": _time.strftime("%Y-%m-%dT%H:%M:%S"), "slug": slug,
                                          "count": len(_bad), "tokens": sorted({t for t, _ in _bad})}) + "\n")
            except Exception:
                pass
            continue

        print(f"  Processing: {slug}")
        faqs = extract_faqs_from_content(content)
        post_entry = build_post_entry(slug, content)
        faq_entry = build_faq_schema_entry(slug, faqs) if faqs else ""

        title = extract_title(content)
        excerpt = extract_excerpt(content)
        rt = read_time(content)
        cat = category_from_slug(slug)

        success = insert_into_blog_page(slug, post_entry, faq_entry)
        if success:
            insert_listing_entry(slug, title, excerpt, cat, rt)
            insert_sitemap_entry(slug)
            newly_inserted.append(slug)
            inserted.add(slug)
            print(f"  ✅ Inserted: {slug} ({len(faqs)} FAQs)")
        else:
            print(f"  ⚠️  Skipped: {slug}")

    if not newly_inserted:
        print("No new posts inserted.")
        return 0

    # Fast syntax check — no full build (Vercel builds on push, CI validates)
    # Just verify TypeScript can parse the modified files (~2s vs ~16s full build)
    print(f"\nSyntax check ({len(newly_inserted)} new posts)...")
    result = subprocess.run(
        ["npx", "tsc", "--noEmit"],
        cwd=WEBSITE_DIR,
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        errors = (result.stdout + result.stderr)[-2000:]
        print(f"SYNTAX CHECK FAILED:\n{errors}")
        # Revert blog files so next run can retry cleanly
        subprocess.run(
            ["git", "checkout", "HEAD", "--",
             "src/app/blog/[slug]/page.tsx", "src/app/blog/page.tsx", "src/app/sitemap.ts"],
            cwd=WEBSITE_DIR,
        )
        print("Reverted blog files — slugs NOT marked inserted, will retry next run")
        return 1
    print("Syntax: OK")

    # §386/§384 — HARD branch guard. `git push origin main` from a feature
    # branch silently no-ops, so commits land on the wrong branch and never
    # deploy. Refuse to commit blog posts unless HEAD is exactly `main`.
    branch_result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=WEBSITE_DIR, capture_output=True, text=True,
    )
    current_branch = branch_result.stdout.strip()
    if current_branch != "main":
        print(
            f"❌ §386/§384: refusing to commit blog posts — HEAD is "
            f"'{current_branch}', not main",
            file=sys.stderr,
        )
        sys.exit(1)

    # §343/§377 belt-and-braces: full-file sanitise sweep before the overnight push.
    # The per-post insertion guard (build_post_entry) already strips each new post, but
    # this idempotent, source-only sweep (no build, cannot abort) guarantees the WHOLE
    # page.tsx that ships is leak-free — covering any manual edit or concurrent drift.
    # The overnight path bypasses deploy.sh's rendered gate, so this is its clean-on-push
    # guarantee. The §357 daily build+scan sweep is the ≤24h rendered backstop.
    subprocess.run(
        [sys.executable, str(Path(__file__).parent / "blog_content_sanitiser.py"), "--apply"],
        cwd=WEBSITE_DIR, check=False,
    )
    subprocess.run(
        ["git", "add", "--", "src/app/blog/", "src/app/sitemap.ts"],
        cwd=WEBSITE_DIR, check=True,
    )
    msg = f"feat: {len(newly_inserted)} blog posts auto-inserted (overnight Haiku batch)"

    # Bug A fix (10/06/2026): a pre-commit hook rejection (§300/§377 IP-leak gate)
    # used to raise CalledProcessError here, leaving the batch STAGED but never
    # committed — a silent orphan that re-failed every run (the IP-leak commit
    # deadlock). New behaviour: commit; if the hook rejects, clean-the-leak ONCE
    # (the widened sanitiser) and retry; if it STILL rejects, fail LOUD and
    # un-stage so we never leave a silent staged orphan (a human/§357 resolves it).
    # NOT a blunt `git checkout HEAD` — page.tsx is monolithic, so a revert would
    # nuke the whole batch (good posts with the leaky one) and doom-loop.
    def _commit_with_heal(message):
        r = subprocess.run(["git", "commit", "-m", message],
                           cwd=WEBSITE_DIR, capture_output=True, text=True)
        if r.returncode == 0:
            return True
        print("⚠️  commit rejected (likely §300/§377 IP-leak hook) — one clean-the-leak "
              f"heal attempt:\n{(r.stdout + r.stderr)[-800:]}", file=sys.stderr)
        subprocess.run(
            [sys.executable, str(Path(__file__).parent / "blog_content_sanitiser.py"), "--apply"],
            cwd=WEBSITE_DIR, check=False,
        )
        subprocess.run(["git", "add", "--", "src/app/blog/", "src/app/sitemap.ts"],
                       cwd=WEBSITE_DIR, check=False)
        r2 = subprocess.run(["git", "commit", "-m", message],
                            cwd=WEBSITE_DIR, capture_output=True, text=True)
        if r2.returncode == 0:
            print("✅ commit succeeded after clean-the-leak heal")
            return True
        print("❌ §313 commit STILL rejected after heal — un-staging blog files so no "
              f"silent staged orphan remains; manual review required:\n{(r2.stdout + r2.stderr)[-800:]}",
              file=sys.stderr)
        # Un-stage only (keep edits on disk so posts aren't lost); next run's
        # sanitiser sweep gets another chance, and the failure is LOUD not silent.
        subprocess.run(["git", "reset", "--", "src/app/blog/", "src/app/sitemap.ts"],
                       cwd=WEBSITE_DIR, check=False)
        return False

    if not _commit_with_heal(msg):
        return 1
    push_result = subprocess.run(
        ["git", "push", "origin", "main"], cwd=WEBSITE_DIR, capture_output=True, text=True,
    )
    if push_result.returncode != 0:
        print(f"PUSH FAILED:\n{push_result.stderr[-1000:]}")
        return 1

    # Only save inserted.json AFTER successful build + push
    save_inserted(inserted)
    print(f"Committed + pushed: {', '.join(newly_inserted)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
